//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAVELANCAR.hotel_mawar_melati_service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="kamar", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class kamar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int free_breakfastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int free_wifiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int harga_akhir_pekanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int harga_hari_biasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jumlah_guestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jumlah_tersediaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kategoriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TRAVELANCAR.hotel_mawar_melati_service.pemesanan[] pemesananField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int free_breakfast {
            get {
                return this.free_breakfastField;
            }
            set {
                if ((this.free_breakfastField.Equals(value) != true)) {
                    this.free_breakfastField = value;
                    this.RaisePropertyChanged("free_breakfast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int free_wifi {
            get {
                return this.free_wifiField;
            }
            set {
                if ((this.free_wifiField.Equals(value) != true)) {
                    this.free_wifiField = value;
                    this.RaisePropertyChanged("free_wifi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int harga_akhir_pekan {
            get {
                return this.harga_akhir_pekanField;
            }
            set {
                if ((this.harga_akhir_pekanField.Equals(value) != true)) {
                    this.harga_akhir_pekanField = value;
                    this.RaisePropertyChanged("harga_akhir_pekan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int harga_hari_biasa {
            get {
                return this.harga_hari_biasaField;
            }
            set {
                if ((this.harga_hari_biasaField.Equals(value) != true)) {
                    this.harga_hari_biasaField = value;
                    this.RaisePropertyChanged("harga_hari_biasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jumlah_guest {
            get {
                return this.jumlah_guestField;
            }
            set {
                if ((this.jumlah_guestField.Equals(value) != true)) {
                    this.jumlah_guestField = value;
                    this.RaisePropertyChanged("jumlah_guest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jumlah_tersedia {
            get {
                return this.jumlah_tersediaField;
            }
            set {
                if ((this.jumlah_tersediaField.Equals(value) != true)) {
                    this.jumlah_tersediaField = value;
                    this.RaisePropertyChanged("jumlah_tersedia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kategori {
            get {
                return this.kategoriField;
            }
            set {
                if ((object.ReferenceEquals(this.kategoriField, value) != true)) {
                    this.kategoriField = value;
                    this.RaisePropertyChanged("kategori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TRAVELANCAR.hotel_mawar_melati_service.pemesanan[] pemesanan {
            get {
                return this.pemesananField;
            }
            set {
                if ((object.ReferenceEquals(this.pemesananField, value) != true)) {
                    this.pemesananField = value;
                    this.RaisePropertyChanged("pemesanan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="pemesanan", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class pemesanan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_kamarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TRAVELANCAR.hotel_mawar_melati_service.kamar kamarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kode_bookingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_pemesanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tanggal_bookingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tanggal_check_inField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tanggal_check_outField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int total_hargaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_kamar {
            get {
                return this.id_kamarField;
            }
            set {
                if ((this.id_kamarField.Equals(value) != true)) {
                    this.id_kamarField = value;
                    this.RaisePropertyChanged("id_kamar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TRAVELANCAR.hotel_mawar_melati_service.kamar kamar {
            get {
                return this.kamarField;
            }
            set {
                if ((object.ReferenceEquals(this.kamarField, value) != true)) {
                    this.kamarField = value;
                    this.RaisePropertyChanged("kamar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kode_booking {
            get {
                return this.kode_bookingField;
            }
            set {
                if ((object.ReferenceEquals(this.kode_bookingField, value) != true)) {
                    this.kode_bookingField = value;
                    this.RaisePropertyChanged("kode_booking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_pemesan {
            get {
                return this.nama_pemesanField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_pemesanField, value) != true)) {
                    this.nama_pemesanField = value;
                    this.RaisePropertyChanged("nama_pemesan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tanggal_booking {
            get {
                return this.tanggal_bookingField;
            }
            set {
                if ((this.tanggal_bookingField.Equals(value) != true)) {
                    this.tanggal_bookingField = value;
                    this.RaisePropertyChanged("tanggal_booking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tanggal_check_in {
            get {
                return this.tanggal_check_inField;
            }
            set {
                if ((this.tanggal_check_inField.Equals(value) != true)) {
                    this.tanggal_check_inField = value;
                    this.RaisePropertyChanged("tanggal_check_in");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tanggal_check_out {
            get {
                return this.tanggal_check_outField;
            }
            set {
                if ((this.tanggal_check_outField.Equals(value) != true)) {
                    this.tanggal_check_outField = value;
                    this.RaisePropertyChanged("tanggal_check_out");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total_harga {
            get {
                return this.total_hargaField;
            }
            set {
                if ((this.total_hargaField.Equals(value) != true)) {
                    this.total_hargaField = value;
                    this.RaisePropertyChanged("total_harga");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kodeBookingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kodeBooking {
            get {
                return this.kodeBookingField;
            }
            set {
                if ((object.ReferenceEquals(this.kodeBookingField, value) != true)) {
                    this.kodeBookingField = value;
                    this.RaisePropertyChanged("kodeBooking");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="hotel_mawar_melati_service.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getKamar", ReplyAction="http://tempuri.org/IService/getKamarResponse")]
        TRAVELANCAR.hotel_mawar_melati_service.kamar[] getKamar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getKamar", ReplyAction="http://tempuri.org/IService/getKamarResponse")]
        System.Threading.Tasks.Task<TRAVELANCAR.hotel_mawar_melati_service.kamar[]> getKamarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getPemesanan", ReplyAction="http://tempuri.org/IService/getPemesananResponse")]
        TRAVELANCAR.hotel_mawar_melati_service.pemesanan[] getPemesanan(string nama);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getPemesanan", ReplyAction="http://tempuri.org/IService/getPemesananResponse")]
        System.Threading.Tasks.Task<TRAVELANCAR.hotel_mawar_melati_service.pemesanan[]> getPemesananAsync(string nama);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/booking", ReplyAction="http://tempuri.org/IService/bookingResponse")]
        TRAVELANCAR.hotel_mawar_melati_service.CompositeType booking(System.DateTime tanggal_check_in, System.DateTime tanggal_check_out, string nama, int idKamar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/booking", ReplyAction="http://tempuri.org/IService/bookingResponse")]
        System.Threading.Tasks.Task<TRAVELANCAR.hotel_mawar_melati_service.CompositeType> bookingAsync(System.DateTime tanggal_check_in, System.DateTime tanggal_check_out, string nama, int idKamar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : TRAVELANCAR.hotel_mawar_melati_service.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<TRAVELANCAR.hotel_mawar_melati_service.IService>, TRAVELANCAR.hotel_mawar_melati_service.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TRAVELANCAR.hotel_mawar_melati_service.kamar[] getKamar() {
            return base.Channel.getKamar();
        }
        
        public System.Threading.Tasks.Task<TRAVELANCAR.hotel_mawar_melati_service.kamar[]> getKamarAsync() {
            return base.Channel.getKamarAsync();
        }
        
        public TRAVELANCAR.hotel_mawar_melati_service.pemesanan[] getPemesanan(string nama) {
            return base.Channel.getPemesanan(nama);
        }
        
        public System.Threading.Tasks.Task<TRAVELANCAR.hotel_mawar_melati_service.pemesanan[]> getPemesananAsync(string nama) {
            return base.Channel.getPemesananAsync(nama);
        }
        
        public TRAVELANCAR.hotel_mawar_melati_service.CompositeType booking(System.DateTime tanggal_check_in, System.DateTime tanggal_check_out, string nama, int idKamar) {
            return base.Channel.booking(tanggal_check_in, tanggal_check_out, nama, idKamar);
        }
        
        public System.Threading.Tasks.Task<TRAVELANCAR.hotel_mawar_melati_service.CompositeType> bookingAsync(System.DateTime tanggal_check_in, System.DateTime tanggal_check_out, string nama, int idKamar) {
            return base.Channel.bookingAsync(tanggal_check_in, tanggal_check_out, nama, idKamar);
        }
    }
}
