//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAVELANCAR.bank_konservatif_service {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class NonexistentEntityException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="bank_konservatif_service.KonservatifService")]
    public interface KonservatifService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/KonservatifService/transferRequest", ReplyAction="http://service/KonservatifService/transferResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TRAVELANCAR.bank_konservatif_service.NonexistentEntityException), Action="http://service/KonservatifService/transfer/Fault/NonexistentEntityException", Name="NonexistentEntityException")]
        [System.ServiceModel.FaultContractAttribute(typeof(TRAVELANCAR.bank_konservatif_service.Exception), Action="http://service/KonservatifService/transfer/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TRAVELANCAR.bank_konservatif_service.transferResponse transfer(TRAVELANCAR.bank_konservatif_service.transferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/KonservatifService/transferRequest", ReplyAction="http://service/KonservatifService/transferResponse")]
        System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.transferResponse> transferAsync(TRAVELANCAR.bank_konservatif_service.transferRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/KonservatifService/helloRequest", ReplyAction="http://service/KonservatifService/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TRAVELANCAR.bank_konservatif_service.helloResponse hello(TRAVELANCAR.bank_konservatif_service.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/KonservatifService/helloRequest", ReplyAction="http://service/KonservatifService/helloResponse")]
        System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.helloResponse> helloAsync(TRAVELANCAR.bank_konservatif_service.helloRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/KonservatifService/cekTransaksiMasukRequest", ReplyAction="http://service/KonservatifService/cekTransaksiMasukResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TRAVELANCAR.bank_konservatif_service.cekTransaksiMasukResponse cekTransaksiMasuk(TRAVELANCAR.bank_konservatif_service.cekTransaksiMasukRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/KonservatifService/cekTransaksiMasukRequest", ReplyAction="http://service/KonservatifService/cekTransaksiMasukResponse")]
        System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.cekTransaksiMasukResponse> cekTransaksiMasukAsync(TRAVELANCAR.bank_konservatif_service.cekTransaksiMasukRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/KonservatifService/loginRequest", ReplyAction="http://service/KonservatifService/loginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TRAVELANCAR.bank_konservatif_service.loginResponse login(TRAVELANCAR.bank_konservatif_service.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/KonservatifService/loginRequest", ReplyAction="http://service/KonservatifService/loginResponse")]
        System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.loginResponse> loginAsync(TRAVELANCAR.bank_konservatif_service.loginRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/KonservatifService/cekSaldoRequest", ReplyAction="http://service/KonservatifService/cekSaldoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TRAVELANCAR.bank_konservatif_service.cekSaldoResponse cekSaldo(TRAVELANCAR.bank_konservatif_service.cekSaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/KonservatifService/cekSaldoRequest", ReplyAction="http://service/KonservatifService/cekSaldoResponse")]
        System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.cekSaldoResponse> cekSaldoAsync(TRAVELANCAR.bank_konservatif_service.cekSaldoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transfer", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class transferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int jumlah;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_pengirim;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kode_transaksi;
        
        public transferRequest() {
        }
        
        public transferRequest(int jumlah, int id_pengirim, string kode_transaksi) {
            this.jumlah = jumlah;
            this.id_pengirim = id_pengirim;
            this.kode_transaksi = kode_transaksi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transferResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class transferResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public transferResponse() {
        }
        
        public transferResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cekTransaksiMasuk", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class cekTransaksiMasukRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kode_transaksi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int jumlah;
        
        public cekTransaksiMasukRequest() {
        }
        
        public cekTransaksiMasukRequest(string kode_transaksi, int jumlah) {
            this.kode_transaksi = kode_transaksi;
            this.jumlah = jumlah;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cekTransaksiMasukResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class cekTransaksiMasukResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public cekTransaksiMasukResponse() {
        }
        
        public cekTransaksiMasukResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomor_kartu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomor_pin;
        
        public loginRequest() {
        }
        
        public loginRequest(string nomor_kartu, string nomor_pin) {
            this.nomor_kartu = nomor_kartu;
            this.nomor_pin = nomor_pin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public loginResponse() {
        }
        
        public loginResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cekSaldo", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class cekSaldoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_nasabah;
        
        public cekSaldoRequest() {
        }
        
        public cekSaldoRequest(int id_nasabah) {
            this.id_nasabah = id_nasabah;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cekSaldoResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class cekSaldoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public cekSaldoResponse() {
        }
        
        public cekSaldoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KonservatifServiceChannel : TRAVELANCAR.bank_konservatif_service.KonservatifService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KonservatifServiceClient : System.ServiceModel.ClientBase<TRAVELANCAR.bank_konservatif_service.KonservatifService>, TRAVELANCAR.bank_konservatif_service.KonservatifService {
        
        public KonservatifServiceClient() {
        }
        
        public KonservatifServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KonservatifServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KonservatifServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KonservatifServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRAVELANCAR.bank_konservatif_service.transferResponse TRAVELANCAR.bank_konservatif_service.KonservatifService.transfer(TRAVELANCAR.bank_konservatif_service.transferRequest request) {
            return base.Channel.transfer(request);
        }
        
        public int transfer(int jumlah, int id_pengirim, string kode_transaksi) {
            TRAVELANCAR.bank_konservatif_service.transferRequest inValue = new TRAVELANCAR.bank_konservatif_service.transferRequest();
            inValue.jumlah = jumlah;
            inValue.id_pengirim = id_pengirim;
            inValue.kode_transaksi = kode_transaksi;
            TRAVELANCAR.bank_konservatif_service.transferResponse retVal = ((TRAVELANCAR.bank_konservatif_service.KonservatifService)(this)).transfer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.transferResponse> TRAVELANCAR.bank_konservatif_service.KonservatifService.transferAsync(TRAVELANCAR.bank_konservatif_service.transferRequest request) {
            return base.Channel.transferAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.transferResponse> transferAsync(int jumlah, int id_pengirim, string kode_transaksi) {
            TRAVELANCAR.bank_konservatif_service.transferRequest inValue = new TRAVELANCAR.bank_konservatif_service.transferRequest();
            inValue.jumlah = jumlah;
            inValue.id_pengirim = id_pengirim;
            inValue.kode_transaksi = kode_transaksi;
            return ((TRAVELANCAR.bank_konservatif_service.KonservatifService)(this)).transferAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRAVELANCAR.bank_konservatif_service.helloResponse TRAVELANCAR.bank_konservatif_service.KonservatifService.hello(TRAVELANCAR.bank_konservatif_service.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            TRAVELANCAR.bank_konservatif_service.helloRequest inValue = new TRAVELANCAR.bank_konservatif_service.helloRequest();
            inValue.name = name;
            TRAVELANCAR.bank_konservatif_service.helloResponse retVal = ((TRAVELANCAR.bank_konservatif_service.KonservatifService)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.helloResponse> TRAVELANCAR.bank_konservatif_service.KonservatifService.helloAsync(TRAVELANCAR.bank_konservatif_service.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.helloResponse> helloAsync(string name) {
            TRAVELANCAR.bank_konservatif_service.helloRequest inValue = new TRAVELANCAR.bank_konservatif_service.helloRequest();
            inValue.name = name;
            return ((TRAVELANCAR.bank_konservatif_service.KonservatifService)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRAVELANCAR.bank_konservatif_service.cekTransaksiMasukResponse TRAVELANCAR.bank_konservatif_service.KonservatifService.cekTransaksiMasuk(TRAVELANCAR.bank_konservatif_service.cekTransaksiMasukRequest request) {
            return base.Channel.cekTransaksiMasuk(request);
        }
        
        public int cekTransaksiMasuk(string kode_transaksi, int jumlah) {
            TRAVELANCAR.bank_konservatif_service.cekTransaksiMasukRequest inValue = new TRAVELANCAR.bank_konservatif_service.cekTransaksiMasukRequest();
            inValue.kode_transaksi = kode_transaksi;
            inValue.jumlah = jumlah;
            TRAVELANCAR.bank_konservatif_service.cekTransaksiMasukResponse retVal = ((TRAVELANCAR.bank_konservatif_service.KonservatifService)(this)).cekTransaksiMasuk(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.cekTransaksiMasukResponse> TRAVELANCAR.bank_konservatif_service.KonservatifService.cekTransaksiMasukAsync(TRAVELANCAR.bank_konservatif_service.cekTransaksiMasukRequest request) {
            return base.Channel.cekTransaksiMasukAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.cekTransaksiMasukResponse> cekTransaksiMasukAsync(string kode_transaksi, int jumlah) {
            TRAVELANCAR.bank_konservatif_service.cekTransaksiMasukRequest inValue = new TRAVELANCAR.bank_konservatif_service.cekTransaksiMasukRequest();
            inValue.kode_transaksi = kode_transaksi;
            inValue.jumlah = jumlah;
            return ((TRAVELANCAR.bank_konservatif_service.KonservatifService)(this)).cekTransaksiMasukAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRAVELANCAR.bank_konservatif_service.loginResponse TRAVELANCAR.bank_konservatif_service.KonservatifService.login(TRAVELANCAR.bank_konservatif_service.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public int login(string nomor_kartu, string nomor_pin) {
            TRAVELANCAR.bank_konservatif_service.loginRequest inValue = new TRAVELANCAR.bank_konservatif_service.loginRequest();
            inValue.nomor_kartu = nomor_kartu;
            inValue.nomor_pin = nomor_pin;
            TRAVELANCAR.bank_konservatif_service.loginResponse retVal = ((TRAVELANCAR.bank_konservatif_service.KonservatifService)(this)).login(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.loginResponse> TRAVELANCAR.bank_konservatif_service.KonservatifService.loginAsync(TRAVELANCAR.bank_konservatif_service.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.loginResponse> loginAsync(string nomor_kartu, string nomor_pin) {
            TRAVELANCAR.bank_konservatif_service.loginRequest inValue = new TRAVELANCAR.bank_konservatif_service.loginRequest();
            inValue.nomor_kartu = nomor_kartu;
            inValue.nomor_pin = nomor_pin;
            return ((TRAVELANCAR.bank_konservatif_service.KonservatifService)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRAVELANCAR.bank_konservatif_service.cekSaldoResponse TRAVELANCAR.bank_konservatif_service.KonservatifService.cekSaldo(TRAVELANCAR.bank_konservatif_service.cekSaldoRequest request) {
            return base.Channel.cekSaldo(request);
        }
        
        public int cekSaldo(int id_nasabah) {
            TRAVELANCAR.bank_konservatif_service.cekSaldoRequest inValue = new TRAVELANCAR.bank_konservatif_service.cekSaldoRequest();
            inValue.id_nasabah = id_nasabah;
            TRAVELANCAR.bank_konservatif_service.cekSaldoResponse retVal = ((TRAVELANCAR.bank_konservatif_service.KonservatifService)(this)).cekSaldo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.cekSaldoResponse> TRAVELANCAR.bank_konservatif_service.KonservatifService.cekSaldoAsync(TRAVELANCAR.bank_konservatif_service.cekSaldoRequest request) {
            return base.Channel.cekSaldoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRAVELANCAR.bank_konservatif_service.cekSaldoResponse> cekSaldoAsync(int id_nasabah) {
            TRAVELANCAR.bank_konservatif_service.cekSaldoRequest inValue = new TRAVELANCAR.bank_konservatif_service.cekSaldoRequest();
            inValue.id_nasabah = id_nasabah;
            return ((TRAVELANCAR.bank_konservatif_service.KonservatifService)(this)).cekSaldoAsync(inValue);
        }
    }
}
