//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAVELANCAR.bank_bung_service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="frontend.controllers.ApiControllerPort", Namespace="http://localhost:83/bankbung/advanced/frontend/web/index.php?r=api%2Findex&ws=1", ConfigurationName="bank_bung_service.frontendcontrollersApiControllerPort")]
    public interface frontendcontrollersApiControllerPort {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://localhost:83/bankbung/advanced/frontend/web/index.php?r=api%2Findex&amp;ws=1) of message getIndexRequest does not match the default value (http://localhost:83/bankbung/advanced/frontend/web/index.php?r=api%2Findex&ws=1)
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:83/bankbung/advanced/frontend/web/index.php?r=api%2Findex&ws=1#g" +
            "etIndex", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TRAVELANCAR.bank_bung_service.getIndexResponse getIndex(TRAVELANCAR.bank_bung_service.getIndexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:83/bankbung/advanced/frontend/web/index.php?r=api%2Findex&ws=1#g" +
            "etIndex", ReplyAction="*")]
        System.Threading.Tasks.Task<TRAVELANCAR.bank_bung_service.getIndexResponse> getIndexAsync(TRAVELANCAR.bank_bung_service.getIndexRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getIndex", WrapperNamespace="http://localhost:83/bankbung/advanced/frontend/web/index.php?r=api%2Findex&amp;ws" +
        "=1", IsWrapped=true)]
    public partial class getIndexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public object kodetransaksi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public object jumlah;
        
        public getIndexRequest() {
        }
        
        public getIndexRequest(object kodetransaksi, object jumlah) {
            this.kodetransaksi = kodetransaksi;
            this.jumlah = jumlah;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getIndexResponse", WrapperNamespace="http://localhost:83/bankbung/advanced/frontend/web/index.php?r=api%2Findex&amp;ws" +
        "=1", IsWrapped=true)]
    public partial class getIndexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public getIndexResponse() {
        }
        
        public getIndexResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface frontendcontrollersApiControllerPortChannel : TRAVELANCAR.bank_bung_service.frontendcontrollersApiControllerPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class frontendcontrollersApiControllerPortClient : System.ServiceModel.ClientBase<TRAVELANCAR.bank_bung_service.frontendcontrollersApiControllerPort>, TRAVELANCAR.bank_bung_service.frontendcontrollersApiControllerPort {
        
        public frontendcontrollersApiControllerPortClient() {
        }
        
        public frontendcontrollersApiControllerPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public frontendcontrollersApiControllerPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public frontendcontrollersApiControllerPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public frontendcontrollersApiControllerPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRAVELANCAR.bank_bung_service.getIndexResponse TRAVELANCAR.bank_bung_service.frontendcontrollersApiControllerPort.getIndex(TRAVELANCAR.bank_bung_service.getIndexRequest request) {
            return base.Channel.getIndex(request);
        }
        
        public string getIndex(object kodetransaksi, object jumlah) {
            TRAVELANCAR.bank_bung_service.getIndexRequest inValue = new TRAVELANCAR.bank_bung_service.getIndexRequest();
            inValue.kodetransaksi = kodetransaksi;
            inValue.jumlah = jumlah;
            TRAVELANCAR.bank_bung_service.getIndexResponse retVal = ((TRAVELANCAR.bank_bung_service.frontendcontrollersApiControllerPort)(this)).getIndex(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TRAVELANCAR.bank_bung_service.getIndexResponse> TRAVELANCAR.bank_bung_service.frontendcontrollersApiControllerPort.getIndexAsync(TRAVELANCAR.bank_bung_service.getIndexRequest request) {
            return base.Channel.getIndexAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRAVELANCAR.bank_bung_service.getIndexResponse> getIndexAsync(object kodetransaksi, object jumlah) {
            TRAVELANCAR.bank_bung_service.getIndexRequest inValue = new TRAVELANCAR.bank_bung_service.getIndexRequest();
            inValue.kodetransaksi = kodetransaksi;
            inValue.jumlah = jumlah;
            return ((TRAVELANCAR.bank_bung_service.frontendcontrollersApiControllerPort)(this)).getIndexAsync(inValue);
        }
    }
}
