//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class pinguin_airEntities3 : DbContext
{
    public pinguin_airEntities3()
        : base("name=pinguin_airEntities3")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<penerbangan> penerbangan { get; set; }
    public DbSet<penumpang> penumpang { get; set; }
    public DbSet<sysdiagrams> sysdiagrams { get; set; }
    public DbSet<tiket> tiket { get; set; }
}
